language: go
go:
- 1.8
notifications:
  email: false
env:
  global:
    secure: aQxh4JW9PgwB1Df3Xm5d89lquwjWzqR57VV38HPI7Bk9P/cXU045QGHncDJsT+TROFM7XF9PM0p2SKB/q8h808c0/uI1v40XVEL1Dja5h26rafAZHO+FJenndAsnVdN49dUOzD0vd/QY75V90Nx+V+cCbpOfQW2SlCDfEPUD9CXo0EgkKiI8LA+HZmy+sPw7FOhC9kdxeGd6KFaJ1fGs5+HG7gOG4ilFftMzVUQwAAz05o0kDnHFzxpZ7vF5Hw6drasbty8cwblS5kcVoMMhjIBKISHs0miO5XJH1eGvujJZFLdOWl7ZPmuBrD0TncMh2hrWlO3WSwUmJfubAR7iJOqZ++Fj4MM/jV5kEg7lQsz5ga5tOPWZyMxAgIHu6o+Lna2AWlBkSFpPjw7QH801NNl894WMhGTzUbVCCpD6/BEEDl7act5hKJ3hq6MaT5/ZXyd1mHby77vgMEX2N9GeGwrhRBmt4iRoslrIhbPFL0ChBob7WkKSD5wKMKthmEXH53OuS9LrFh2JGBH/dXk/26L1Hdb/10LVSiI9IvSBhXejJV3ud37GwLb4kCIwN90LeTPIFRT0XfWNPkkQfznDm8bAehQgeRbgSYswBarfEitLc2owOsoEQ5WOTyWhps1U/oTHONYX/HAEGDFcqbo0OdDyQxqQ9D/mWSgLkkUAYrs=

